### ISSUE TITLE
Error when loading model

### ISSUE THREAD

**Issue by kawu** [360er0/COMBO#6]
Hi, I'm trying to use `COMBO` with a pre-trained model (more precisely, `model.pl_sz.pkl`).  Unfortunately, it seems that loading the model doesn't work, I get the following error:
```
Using TensorFlow backend.
2020-03-02 14:13:29.268039: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-02 14:13:29.272319: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1800000000 Hz
2020-03-02 14:13:29.272960: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x10ea8d0 executing computations on platform Host. Devices:
2020-03-02 14:13:29.272981: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Load model 2020-03-02 14:13:29
Traceback (most recent call last):
  File "main.py", line 295, in <module>
    parser = joblib.load(params.model_file)
  File "/home/kuba/.local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 605, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/kuba/.local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 0
```

I've tried with another model for Polish (`model_A_semi.pkl`) and the result is the same.  What could be the reason behind this problem?

I used `requirements.txt`(`pip3 install -r requirements.txt`) to install all the dependencies.

**Comment by swapnilnikule** [comment]
i am facing the same error issue

**Comment by 360er0** [comment]
Thanks for reporting this. I've fixed the bug and it should be working fine now.
