### ISSUE TITLE
Missing feats?

### ISSUE THREAD

**Issue by ryszardtuora** [360er0/COMBO#8]
I am having trouble with using trained models for prediction. If I understand it correctly, the problem occurs when a feature appears in the data to parse, which has not appeared in the training data for the model used.

Here is the traceback:
```
Traceback (most recent call last):
  File "COMBO-master/main.py", line 231, in <module>
    pred_valid = parser.predict(valid_data)
  File "/home/aleczkowski/ud_vs_sud/COMBO-master/parser.py", line 203, in predict
    for batch in self.batchify_X(trees):
  File "/home/aleczkowski/ud_vs_sud/COMBO-master/parser.py", line 48, in batchify_X
    raw = self.features_factory.transform(trees)
  File "/home/aleczkowski/ud_vs_sud/COMBO-master/encoders.py", line 458, in transform
    encoded_trees = encoder.transform(trees)
  File "/home/aleczkowski/ud_vs_sud/COMBO-master/encoders.py", line 257, in transform
    out_feat[val2idx[val]] = 1.0
KeyError: 'Mid'
```

**Comment by 360er0** [comment]
Yes, if the feature was not available during training then model won't work. This is a bug, the unknown feature should be ignored. I will fix this.
